<?php

use Illuminate\Database\Seeder;

class ProductTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        DB::table('products')->insert([
            [
                'product' => 'Dine',
                'product_alias' => 'dine',
                'product_unit' => 'Unit 2',
                'product_style' => '',
                'category_id' => 1,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,

                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Pastries',
                'product_alias' => 'pastries',
                'product_unit' => 'Unit 2',
                'product_style' => '',
                'category_id' => 1,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,

                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Desserts',
                'product_alias' => 'desserts',
                'product_unit' => 'Unit 2',
                'product_style' => '',
                'category_id' => 1,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,

                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Beverages',
                'product_alias' => 'beverages',
                'product_unit' => 'Unit 2',
                'product_style' => '',
                'category_id' => 1,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,

                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Coffee & Tea',
                'product_alias' => 'coffee_and_tea',
                'product_unit' => 'Unit 2',
                'product_style' => '',
                'category_id' => 1,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,

                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Confectionary',
                'product_alias' => 'confectionary',
                'product_unit' => 'Unit 2',
                'product_style' => '',
                'category_id' => 1,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,

                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Roastery',
                'product_alias' => 'roastery',
                'product_unit' => 'Unit 2',
                'product_style' => '',
                'category_id' => 1,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,

                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Catering',
                'product_alias' => 'catering',
                'product_unit' => 'Unit 2',
                'product_style' => '',
                'category_id' => 1,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ],
            // Category 2
            [
                'product' => 'Design & Interiors',
                'product_alias' => 'design_and_Interiors',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 2,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Booking',
                'product_alias' => 'booking',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 2,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Hospitality',
                'product_alias' => 'hospitality',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 2,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Catering',
                'product_alias' => 'catering',
                'product_unit' => 'Unit 2',
                'product_style' => '',
                'category_id' => 2,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Entertaining',
                'product_alias' => 'entertaining',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 2,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Flower arrangements',
                'product_alias' => 'flower_arrangements',
                'product_unit' => 'Unit 2',
                'product_style' => '',
                'category_id' => 2,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Party supplies',
                'product_alias' => 'party supplies',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 2,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ],
            // Category 3
            [
                'product' => 'Gifts',
                'product_alias' => 'gifts',
                'product_unit' => 'Unit 3',
                'product_style' => '',
                'category_id' => 3,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Flowers',
                'product_alias' => 'flowers',
                'product_unit' => 'Unit 2',
                'product_style' => '',
                'category_id' => 3,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ],
            [
                'product' => 'Chocolates',
                'product_alias' => 'chocolates',
                'product_unit' => 'Unit 2',
                'product_style' => '',
                'category_id' => 3,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Packing',
                'product_alias' => 'packing',
                'product_unit' => 'Unit 3',
                'product_style' => '',
                'category_id' => 3,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ],
            // Category 4
            [
                'product' => 'Fragrances and perfumes',
                'product_alias' => 'fragrances_and_perfumes',
                'product_unit' => 'Unit 2',
                'product_style' => '',
                'category_id' => 4,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Makeup and cosmetic products',
                'product_alias' => 'makeup_and_cosmetic_products',
                'product_unit' => 'Unit 2',
                'product_style' => '',
                'category_id' => 4,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Body Care products',
                'product_alias' => 'body_care_products',
                'product_unit' => 'Unit 2',
                'product_style' => '',
                'category_id' => 4,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Hair dressing',
                'product_alias' => 'hair_dressing',
                'product_unit' => 'Unit 2',
                'product_style' => '',
                'category_id' => 4,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Makeup',
                'product_alias' => 'makeup',
                'product_unit' => 'Unit 2',
                'product_style' => '',
                'category_id' => 4,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Facial and Skin care',
                'product_alias' => 'facial_and_skin_care',
                'product_unit' => 'Unit 2',
                'product_style' => '',
                'category_id' => 4,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Manicure and Pedicure',
                'product_alias' => 'manicure_and_pedicure',
                'product_unit' => 'Unit 2',
                'product_style' => '',
                'category_id' => 4,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Henna',
                'product_alias' => 'henna',
                'product_unit' => 'Unit 2',
                'product_style' => '',
                'category_id' => 4,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Spa & Massage',
                'product_alias' => 'spa_and_Massage',
                'product_unit' => 'Unit 2',
                'product_style' => '',
                'category_id' => 4,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ],
            // Category 5
            [
                'product' => 'Tailor and Design',
                'product_alias' => 'tailor_and_design',
                'product_unit' => 'Unit 1',
                'product_style' => '',
                'category_id' => 5,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Women dresses',
                'product_alias' => 'women_dresses',
                'product_unit' => 'Unit 1',
                'product_style' => '',
                'category_id' => 5,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Men clothes',
                'product_alias' => 'men_clothes',
                'product_unit' => 'Unit 1',
                'product_style' => '',
                'category_id' => 5,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Kids clothes',
                'product_alias' => 'kids_clothes',
                'product_unit' => 'Unit 1',
                'product_style' => '',
                'category_id' => 5,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Textiles',
                'product_alias' => 'textiles',
                'product_unit' => 'Unit 1',
                'product_style' => '',
                'category_id' => 5,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Shoes and Bags',
                'product_alias' => 'shoes_and_bags',
                'product_unit' => 'Unit 1',
                'product_style' => '',
                'category_id' => 5,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Jewelry and Accessories',
                'product_alias' => 'jewelry_and_accessories',
                'product_unit' => 'Unit 1',
                'product_style' => '',
                'category_id' => 5,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ],
            //Category 6
            [
                'product' => 'General Clinic',
                'product_alias' => 'general_clinic',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 6,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Dental Clinic',
                'product_alias' => 'dental_clinic',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 6,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Vision Clinic',
                'product_alias' => 'vision_clinic',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 6,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Children Clinic',
                'product_alias' => 'children_clinic',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 6,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Cosmetic Clinic',
                'product_alias' => 'cosmetic_clinic',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 6,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Physical treatment and Therapy',
                'product_alias' => 'physical_treatment_and_therapy',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 6,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Vitamins and supplements',
                'product_alias' => 'vitamins_and_supplements',
                'product_unit' => 'Unit 2',
                'product_style' => '',
                'category_id' => 6,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Pharmaceutical supplies',
                'product_alias' => 'pharmaceutical_supplies',
                'product_unit' => 'Unit 2',
                'product_style' => '',
                'category_id' => 6,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Veterinary',
                'product_alias' => 'veterinary',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 6,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ],
            //category 7
            [
                'product' => 'Interior designing',
                'product_alias' => 'veterinary',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 7,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Furniture',
                'product_alias' => 'furniture',
                'product_unit' => 'Unit 3',
                'product_style' => '',
                'category_id' => 7,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Garden Care and Supplies',
                'product_alias' => 'garden_care_and_supplies',
                'product_unit' => 'Unit 3',
                'product_style' => '',
                'category_id' => 7,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Hardware tools',
                'product_alias' => 'hardware_tools',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 7,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Pets and animals',
                'product_alias' => 'pets_and_animals',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 7,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Storage services',
                'product_alias' => 'storage_services',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 7,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Plumbing',
                'product_alias' => 'plumbing',
                'product_unit' => 'Unit 2',
                'product_style' => '',
                'category_id' => 7,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Cleaning',
                'product_alias' => 'cleaning',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 7,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Carpentering',
                'product_alias' => 'carpentering',
                'product_unit' => 'Unit 3',
                'product_style' => '',
                'category_id' => 7,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Air conditioning Repair and Maintenance',
                'product_alias' => 'air_conditioning_repair_and_maintenance',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 7,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Electrical Repair and Maintenance',
                'product_alias' => 'electrical_repair_and_maintenance',
                'product_unit' => 'Unit 3',
                'product_style' => '',
                'category_id' => 7,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Welding',
                'product_alias' => 'welding',
                'product_unit' => 'Unit 2',
                'product_style' => '',
                'category_id' => 7,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Gas supply',
                'product_alias' => 'gas_supply',
                'product_unit' => 'Unit 2',
                'product_style' => '',
                'category_id' => 7,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Water supply',
                'product_alias' => 'water_supply',
                'product_unit' => 'Unit 2',
                'product_style' => '',
                'category_id' => 7,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ],
            //category 8
            [
                'product' => 'Hotels, Resorts and Villas',
                'product_alias' => 'hotels_Resorts_and_villas',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 8,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Bookings',
                'product_alias' => 'bookings',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 8,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Touring',
                'product_alias' => 'touring',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 8,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Entertaining Activities',
                'product_alias' => 'entertaining_activities',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 8,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ],
            // Category 9
            [
                'product' => 'Cars',
                'product_alias' => 'cars',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 9,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ],
            [
                'product' => 'Motorcycle & Bikes',
                'product_alias' => 'motorcycle_and_bikes',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 9,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Parts and Accessories',
                'product_alias' => 'parts_and_accessories',
                'product_unit' => 'Unit 2',
                'product_style' => '',
                'category_id' => 9,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Car Care and Repair',
                'product_alias' => 'car_care_and_repair',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 9,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Recovery',
                'product_alias' => 'recovery',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 9,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Renting',
                'product_alias' => 'renting',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 9,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ],
            // Category 10
            [
                'product' => 'Computers and Networks and Accessories',
                'product_alias' => 'computers_and_networks_and_accessories',
                'product_unit' => 'Unit 3',
                'product_style' => '',
                'category_id' => 10,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Electronics and Accessories',
                'product_alias' => 'electronics_and_accessories',
                'product_unit' => 'Unit 3',
                'product_style' => '',
                'category_id' => 10,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Electrical equipment and Accessories',
                'product_alias' => 'electrical_equipment_and_accessories',
                'product_unit' => 'Unit 3',
                'product_style' => '',
                'category_id' => 10,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Mobile Phones and Accessories',
                'product_alias' => 'mobile_phones_and_accessories',
                'product_unit' => 'Unit 3',
                'product_style' => '',
                'category_id' => 10,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Repair and Maintenance',
                'product_alias' => 'repair_and_maintenance',
                'product_unit' => 'Unit 3',
                'product_style' => '',
                'category_id' => 10,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ],
            //category 11
            [
                'product' => 'Administration & Secretarial',
                'product_alias' => 'administration_and_secretarial',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 11,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ],
            [
                'product' => 'Stationary, Printing and Publishing',
                'product_alias' => 'stationary_printing_and_publishing',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 11,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Bookstore',
                'product_alias' => 'bookstore',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 11,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Grocery',
                'product_alias' => 'grocery',
                'product_unit' => 'Unit 2',
                'product_style' => '',
                'category_id' => 11,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Butchery',
                'product_alias' => 'butchery',
                'product_unit' => 'Unit 3',
                'product_style' => '',
                'category_id' => 11,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Vegetables and Fruits',
                'product_alias' => 'vegetables_and_fruits',
                'product_unit' => 'Unit 2',
                'product_style' => '',
                'category_id' => 11,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Toys',
                'product_alias' => 'toys',
                'product_unit' => 'Unit 3',
                'product_style' => '',
                'category_id' => 11,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Sports',
                'product_alias' => 'sports',
                'product_unit' => 'Unit 3',
                'product_style' => '',
                'category_id' => 11,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Music',
                'product_alias' => 'music',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 11,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Safety Equipment',
                'product_alias' => 'safety_equipment',
                'product_unit' => 'Unit 3',
                'product_style' => '',
                'category_id' => 11,
                'is_service' => 0,
                'is_home_service' => 0,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Document and Certificate Clearance',
                'product_alias' => 'document_and_certificate_clearance',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 11,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Housemaid',
                'product_alias' => 'housemaid',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 11,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Child daycare',
                'product_alias' => 'child_daycare',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 11,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Nursing',
                'product_alias' => 'nursing',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 11,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Laundry',
                'product_alias' => 'laundry',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 11,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Studio',
                'product_alias' => 'studio',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 11,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Packing and Shipping',
                'product_alias' => 'packing_and_shipping',
                'product_unit' => 'Unit 3',
                'product_style' => '',
                'category_id' => 11,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Creative and Handcrafts',
                'product_alias' => 'creative_and_handcrafts',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 11,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ],
            // Category 12
            [
                'product' => 'Business and Marketing',
                'product_alias' => 'business_and_marketing',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 12,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ],
            [
                'product' => 'Graphic Designs',
                'product_alias' => 'graphic_designs',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 12,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Constructions',
                'product_alias' => 'constructions',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 12,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Legal',
                'product_alias' => 'legal',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 12,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Finance & Accounting',
                'product_alias' => 'finance_and_Accounting',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 12,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ],
            // Category 13
            [
                'product' => 'Quraan Tutor',
                'product_alias' => 'quraan_tutor',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 13,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Pre-Primary Tutor',
                'product_alias' => 'pre_primary_tutor',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 13,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Primary Tutor',
                'product_alias' => 'primary_tutor',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 13,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Secondary Tutor',
                'product_alias' => 'secondary_tutor',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 13,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Higher Tutor',
                'product_alias' => 'higher_tutor',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 13,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Professional training',
                'product_alias' => 'professional_training',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 13,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ], [
                'product' => 'Dancing & Fitness',
                'product_alias' => 'dancing_and_fitnessr',
                'product_unit' => 'NA',
                'product_style' => '',
                'category_id' => 13,
                'is_service' => 0,
                'is_home_service' => 1,
                'is_active' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ],
        ]);
    }
}
